#!/bin/bash
#
# postinstall
#
# Copyright (c) 2020 LogMeIn, Inc. All rights reserved.
# ===========================================================================

    UAParam=${UNATTENDED_PARAMETERS}

    logfile="/tmp/$(date +%Y-%m-%d_%H%M)_unattended_pkg.log"

    printf "%s - postinstall - started\n" "$(date '+%Y-%m-%d %H:%M:%S.000')" >> "${logfile}"
    xattr -w com.logmein.rescue.params "${UAParam}" "/tmp/unattended_mac.app"

    sudo rm "/tmp/params.txt"
    sudo "/tmp/unattended_mac.app/Contents/MacOS/unattended_mac" >> "${logfile}"
#   rm -R /tmp/unattended_mac.app

    printf "%s - postinstall - finished\n" "$(date '+%Y-%m-%d %H:%M:%S.999')" >> "${logfile}"
# ===========================================================================
